### ISSUE TITLE
feat(workshops): Add Getting Setup For Honeycomb

### ISSUE THREAD

**Issue by mirestrepo** [brown-ccv/ccv-website-content#129]
We should add a card for the workshop that we just hosted and related links to docs and videos. Thanks!

**Comment by mirestrepo** [comment]
@RobertGemmaJr  This issue is to create a PR on this repo with this info ;)

**Comment by RobertGemmaJr** [comment]
Haha yes - was just collecting all of the links, will make the PR (:
