### ISSUE TITLE
feat(software): Add card for OMNI and OMNI Client (MyRC+S v2)

### ISSUE THREAD

**Issue by mirestrepo** [brown-ccv/ccv-website-content#30]

**Comment by broarr** [comment]
If you look at the software folder, ther is one yaml file per software. The main README has some info about the validation, which is given by a schema file in schemas/software.yml

We just need to add a new card for OMNI and a separate one for OMNI client (edited) 

Does that make sense?

**Comment by mirestrepo** [comment]
Closed via #39
