### ISSUE TITLE
feat(collaborations): Add past and present collaborations

### ISSUE THREAD

**Issue by ashokrags** [brown-ccv/ccv-website-content#45]

**Comment by JRWallace** [comment]
question: do I want to list resulting publications in this yaml? could I put it in the 'links' category perhaps?

**Comment by mirestrepo** [comment]
@JRWallace is this still relevant? I feel like you did your collaborations already. No?

**Comment by JRWallace** [comment]
We just need to address https://github.com/brown-ccv/ccv-website-content/issues/113 but I can close this one
