### ISSUE TITLE
feat(collaborations): Add past and current collaborations

### ISSUE THREAD

**Issue by paulstey** [brown-ccv/ccv-website-content#64]

**Comment by paulstey** [comment]
Hi @j-stat!! Ashok asked me to create this issue... so I did!

¯\_(ツ)_/¯

**Comment by j-stat** [comment]
Ah, thank you! I will look into this :)

Kind regards,

Jordan

**Comment by mirestrepo** [comment]
What collaborations is this issue referring to?

**Comment by mirestrepo** [comment]
stale
