### ISSUE TITLE
feat(people): add Sahdiah as an intern

### ISSUE THREAD

**Issue by aguang** [brown-ccv/ccv-website-content#85]
@sadface256 please add yourself as an intern to the content. To do so:

 * make a new branch
 * edit the `about/people.yml` with your information in the same style as others on there
 * add your images to the `images` directory
 * commit & push (add something like "close #issue" to the commit
 * open a pull request

**Comment by mirestrepo** [comment]
I'm closing - seems stale, feel free to re-open
